# Generated by Django 2.2 on 2020-08-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMaterial', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPersona', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=21)),
                ('telefono', models.CharField(max_length=20)),
                ('numLibros', models.CharField(max_length=20)),
                ('aduedo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEmpleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('materiale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Materiale')),
                ('editorial', models.CharField(max_length=20)),
            ],
            bases=('biblioteca.materiale',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('materiale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Materiale')),
            ],
            bases=('biblioteca.materiale',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('idd', models.CharField(max_length=20)),
                ('fechaSalida', models.CharField(max_length=20)),
                ('fechaRegreso', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Personia')),
            ],
        ),
    ]
