# Generated by Django 2.2 on 2020-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiale',
            name='status',
            field=models.CharField(choices=[('LI', 'Librado'), ('PR', 'Prestado'), ('AR', 'Arreglandose')], default='LI', max_length=2),
        ),
    ]
