# Generated by Django 2.2 on 2020-08-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personia',
            old_name='aduedo',
            new_name='adeudo',
        ),
    ]
