# Generated by Django 2.2 on 2020-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMaterial', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesore',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fechaRegereso',
            new_name='fechaRegreso',
        ),
    ]
