# Generated by Django 2.2 on 2020-08-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200818_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personia',
        ),
    ]
